import Navbar from '@/components/Navbar';
import './globals.css';
import localFont from 'next/font/local';

import MobileMenu from '@/components/Navbar/MobileNavbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const Gilroy = localFont({
  src: [
    {
      path: './Gilroy-SemiBold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: './Gilroy-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './Gilroy-Bold.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: './Gilroy-Medium.woff',
      weight: '500',
      style: 'normal',
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Gilroy.className}>
        <Navbar />
        <MobileMenu />
        {children}
      </body>
    </html>
  );
}
